Adds :aws_profile as a way to provide credentials
getletterpress/athens pull request #7
Opened 2021-01-28 11:01 UTC by oisin

For multiple AWS accounts and different cross-account roles, users will usually have a `~/.aws/credentials` file with multiple profiles. This PR contains some extra code to allow use of a named `aws_profile` in the `Athens.configure` block.

```ruby
    Athens.configure do |config|
      config.output_location = "s3://bucket/folder"  # Required
      config.aws_profile = "development"
    end
```

2021-02-08 21:17 UTC, cschulte22 requested changes

2021-02-08 21:17 UTC, cschulte22 commented on lib/athens/connection.rb
> +      if (Athens.configuration.aws_profile)
There's no need for the if/else switch here, the `compact` will remove nils from the hash, so you can just set it along with the other fields in the original code

2021-02-08 21:17 UTC, cschulte22 commented on lib/athens/version.rb
> +  VERSION = "0.3.4"
You don't need to do this, I'll take care of bumping the version and updating the changelog on my end when I release.

2021-02-08 21:17 UTC, cschulte22 commented on lib/athens/configuration.rb
> +      @aws_profile = nil
Can you update the README file and document this change?  It'll be helpful for other people who are looking for this option.

2021-05-15 14:06 UTC, oisin commented
Have made the updates. Going to close this PR and open a fresh one (I've changed the name of my branch, a new PR will make things a bit easier)

2021-05-15 14:06 UTC, closed without merging